# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('c_code', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=30)),
                ('t_id', models.IntegerField()),
                ('c_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30)),
                ('s_dob', models.DateField()),
                ('s_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('s_mobile', models.IntegerField()),
                ('s_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=30)),
                ('s_dob', models.DateField()),
                ('s_email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('s_mobile', models.IntegerField()),
                ('s_address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=30)),
                ('t_age', models.IntegerField()),
                ('t_qual', models.CharField(max_length=30)),
            ],
        ),
    ]
