# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estastudy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='s_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
